name: newci

on :
  push: 
  pull_request: 

jobs: 
  newCI: 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}    
      - run: pip install -r requirements.txt
      - run: pytest -v
